# Generated by Django 5.2.2 on 2025-07-08 00:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for background processing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "editing_mode",
                    models.CharField(
                        help_text="Edit mode: copyedit, brevity, etc.", max_length=50
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Raw wikitext content to edit", null=True
                    ),
                ),
                (
                    "article_title",
                    models.CharField(
                        blank=True,
                        help_text="Wikipedia article title",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "section_title",
                    models.CharField(
                        blank=True,
                        help_text="Wikipedia section title",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        blank=True,
                        help_text="LLM provider: google, openai, etc.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        help_text="Specific model used",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("RETRY", "Retry"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Edit results as JSON", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if task failed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When task processing started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When task completed", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of requester", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the task (if authenticated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "edit_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="edit_tasks_status_8ba02f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="edit_tasks_created_31404a_idx"
                    ),
                    models.Index(
                        fields=["celery_task_id"], name="edit_tasks_celery__3db7a5_idx"
                    ),
                ],
            },
        ),
    ]
