# Generated by Django 5.2.2 on 2025-07-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edittask",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="edittask",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="edittask",
            name="progress_data",
            field=models.JSONField(
                blank=True,
                help_text="Progress tracking data during processing",
                null=True,
            ),
        ),
    ]
