name: Deploy EditEngine to Toolforge

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  TOOL_NAME: editengine

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TOOLFORGE_SSH_KEY }}

      - name: Deploy to Toolforge
        uses: appleboy/ssh-action@v1
        with:
          host: login.toolforge.org
          username: ${{ secrets.TOOLFORGE_USERNAME }}
          key: ${{ secrets.TOOLFORGE_SSH_KEY }}
          port: 22
          request_pty: true
          script: |
            become ${{ env.TOOL_NAME }} -- bash -c '
              set -euo pipefail
              toolforge webservice buildservice stop --mount all || echo "Webservice was not running"
              toolforge build start https://github.com/${{ github.repository }}
              toolforge webservice buildservice start --mount all
              echo "Deployment initiated successfully"
            '
